Added required dependencies
virtual-puppet-project/vpuppr pull request #124
Opened 2022-06-19 02:05 UTC by GlitchPhoenix98

Added commands to install dependencies on 3.6 - 3.9 and 3.10.

2022-06-19 17:36 UTC, you-win commented
Thanks for the PR. This is technically in the latest stable release [here](https://github.com/virtual-puppet-project/vpuppr/tree/7627a2bd1d2d0feb498091a9c697a47b28a95073/resources/scripts), but still needs to be restored for master.

I want to avoid polluting the user's global python module environment, so regardless of what version of Python is present, a venv should be used.

2022-06-19 17:37 UTC, you-win commented
Perhaps your PR could be reworded as a manual install step?

2022-06-19 17:39 UTC, GlitchPhoenix98 commented
Sure, I was kinda tired when I wrote the title, so my bad for the wording. Also I did add a guide for the venv.

2022-06-20 03:05 UTC, you-win requested changes

2022-06-20 03:05 UTC, you-win commented on README.md
> +* `pip install onnxruntime opencv-python pillow numpy`
a venv should be used instead of polluting the global python package env

2022-06-20 03:05 UTC, you-win commented on README.md
> +* `cd ~/.local/share/godot/app_userdata/OpenSeeFaceGD`
this should be changed to use the new name of the app: `vpuppr`

2022-06-20 13:45 UTC, GlitchPhoenix98 commented on README.md
> +* `pip install onnxruntime opencv-python pillow numpy`
I agree. I'll add that now.

2022-06-20 17:24 UTC, you-win commented on README.md
> +* `cd ~/.local/share/godot/app_userdata/OpenSeeFaceGD`
The master branch of the project uses a new app name.

The implication being: these instructions will not work for the latest version that's still in development. If left as is, another commit would be needed to change the name

2022-06-20 23:41 UTC, GlitchPhoenix98 commented on README.md
> +* `cd ~/.local/share/godot/app_userdata/OpenSeeFaceGD`
Done

2022-08-02 00:58 UTC, ByteDream requested changes

2022-08-02 00:58 UTC, ByteDream commented on README.md
> +### Python 3.6 - 3.9:
Python 3.6 is [EOL since 23rd December 2021](https://peps.python.org/pep-0494/) and onnxruntime dropped support for it with [v1.11.0](https://github.com/microsoft/onnxruntime/releases/tag/v1.11.0) as well. In [v1.12.0](https://github.com/microsoft/onnxruntime/releases/tag/v1.12.0) onnxruntime added support for python 3.10 to the library.
So consider to bump the version requirement from `3.6 - 3.9` to `3.7 - 3.10` to keep up with the supported versions.

2022-08-02 00:58 UTC, ByteDream commented on README.md
> +### Python 3.10 and above:
If `Python 3.10` is added as supported python version in the section above this header might be changed to `Above Python 3.10` (or something similar).

2022-08-02 17:55 UTC, you-win commented
I agree with the comments from @ByteDream .

For local development (not using the `pyinstaller` version of OpenSeeFace included with the current Linux alpha), the instructions could be consolidated into 1 section for all supported Python versions.

2022-08-04 19:56 UTC, orowith2os commented
Anyone can easily grab the pyinstaller version of openseeface from vpuppr and run it just fine outside if it, it seems, so maybe just provide instructions on how to build that?

2022-09-02 03:22 UTC, you-win commented
vpuppr has had its git refs pruned. Basically, it should be much leaner now when grabbing the source code (from a 200mb download to 100mb). If this PR is still in-progress, please follow these steps:

1. Back up your changes
2. Delete your copies of vpuppr in GitHub and on your computer
3. Re-fork vpuppr
4. Re-apply your changes
5. Re-submit the PR

2022-09-02 03:22 UTC, closed without merging